- hosts: pvenodes
  become: true
  tasks:
  - name: Install Python 3
    raw: python3 -m ensurepip --default-pip
    ignore_errors: yes

  - name: Install python3-pip
    apt:
      name: python3-pip
      state: present
    when: ansible_distribution == 'Debian'

  - name: Install proxmoxer using pip
    pip:
      name: proxmoxer
      executable: python3-pip